---
# Enforces consistent style
printWidth: 80
tabWidth: 2
useTabs: true
semi: true
singleQuote: true
quoteProps: as-needed
jsxSingleQuote: false
trailingComma: all
bracketSpacing: true
bracketSameLine: true
arrowParens: avoid
endOfLine: lf

# Formatting behavior
embeddedLanguageFormatting: auto
htmlWhitespaceSensitivity: css
proseWrap: always
singleAttributePerLine: true
vueIndentScriptAndStyle: false
ignore:
  - node_modules/**
  - dist/**
  - docs/**
  - src/**/*.test.js
  - src/**/*.spec.js
overrides:
  - files: LICENSE
    options:
      parser: markdown
  - files: '*.{yaml,yml}'
    options:
      tabWidth: 2
      useTabs: false
      singleQuote: true
  - files: '*.json'
    options:
      singleQuote: false
