name: Bug report
description: Create a report to help us fix issues with our library
labels: ["bug"]
# title: ''
assignees: dylarcher
body:
  - type: markdown
    attributes:
      value: We appreciate your help with submitting a bug report to make our library better. The more information you provide in the following sections, to better help us understand the issue you are facing, the more effective our response will be while improving your experience with the library.
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: When I run…
    validations:
      required: true
  - type: textarea
    id: to-reproduce
    attributes:
      label: To reproduce
      description: Please share the steps to reproduce the issue you are facing.
      placeholder: |
        e.g.

          1. Installed the library
          2. Imported the module
          3. Called function `foo()`
          4. Get error when calling `bar()`
          5. …
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of the library are you running?
      placeholder: e.g. 0.1.0
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Provide any other context about the problem.
      placeholder: e.g. Add additional details here or insert screenshots/recordings.