name: \U0001F680 Feature Request
description: Suggest an idea for this project
title: "[Idea]: "
labels: [enhancement, feature, request, idea, suggestion, review]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the feature is.
      placeholder: I'm always frustrated when...
    validations:
      required: true
  - type: textarea
    id: problem-solution
    attributes:
      label: Problem/Solution
      description: Is your feature request related to a problem? Please describe the problem and the solution this feature would provide.
      placeholder: The current process for `X` is cumbersome because… This feature would streamline it by…
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered.
      placeholder: I've tried `X`, but it doesn't solve `Y` because…
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [CODE_OF_CONDUCT](../.github/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
