---
name: Checks

on:
  pull_request:
    types: [edited,opened,reopened,synchronize]

jobs:
  checks:
    name: Lint, Format, Test & Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      fail-fast: true
      matrix:
        node-version: [22.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Setup
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          registry-url: https://registry.npmjs.org
          cache: npm

      - name: Install
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Format
        run: npm run format

      - name: Test
        run: npm run test:coverage

      # Uncomment the following step if you want to build the package explicitly.
      # If the 'prepublishOnly' script in package.json already handles this, you can skip this step.
      # If you want to build the package explicitly, uncomment the following step:
      # - name: Build
      #   run: npm run build