---
name: Checks # this workflow is setup to be self-contained

on:
  pull_request:
    types:
      - edited
      - opened
      - ready_for_review
      - reopened
      - review_requested
      - synchronize

jobs:
  checks:
    name: Lint > Format > Test > Build > Bundle
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Setup
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          registry-url: https://registry.npmjs.org
          cache: npm

      - name: Install
        run: |
          npm install typescript dts-bundle-generator @types/node c8 \
            eslint eslint-config-prettier eslint-plugin-markdown \
            eslint-plugin-prettier eslint-plugin-yaml@1.0.3 prettier \
            prettier-plugin-properties @stedi/prettier-plugin-jsonata \
          && npm clean-install \

      - name: Lint
        run: |
          npx eslint --config=./.github/linters/eslint.config.js ./**/*.{js,md,yml,json} \
          --report-unused-disable-directives --continue-on-error \

      - name: Format
        run: |
          npx prettier --config=./.github/linters/.prettierrc.yml ./**/*.{js,md,yml,json} \
          --check --ignore-unknown --no-error-on-unmatched-pattern \

      - name: Test
        run: |
          npx c8 --config=./.github/linters/.c8rc.json -- \
          node --no-warnings --experimental-specifier-resolution=node --inspect-brk \
          test --reporter=spec ./**/*.test.js ./**/*.spec.js \

      - name: Build
        run: |
          npx tsc --minify

      - name: Bundle
        run: |
          npx dts-bundle-generator --config=./.github/linters/dts.config.js \
