---
name: Checks

on:
  pull_request:
    types:
      - edited
      - opened
      - ready_for_review
      - reopened
      - review_requested
      - synchronize

jobs:
  checks:
    name: Lint > Format > Test > Build > Bundle
    strategy:
      fail-fast: true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Setup
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          registry-url: https://registry.npmjs.org
          cache: npm

      - name: Install
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Format
        run: npm run format

    # TODO: setup node:test & c8 for src/** files
    # - name: Test
    #   run: npm run test:coverage

      - name: Build
        run: npm run build

      - name: Bundle
        run: npm run bundle
