---
name: Prettier

on:
<<<<<<<< HEAD:.github/workflows/format.yml
  pull_request:
    types: [edited,opened,reopened,synchronize]

jobs:
  prettier:
    name: Format
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

========
  release:
    types: [published]

jobs:
  publish:
    name: Build & Release
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
    
>>>>>>>> main:.github/workflows/publish.yml
    strategy:
      fail-fast: true
      matrix:
        node-version: [22.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Setup
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          registry-url: https://registry.npmjs.org
          cache: npm

      - name: Install
        run: npm install

<<<<<<<< HEAD:.github/workflows/format.yml
      - name: Format
        run: npm run format
========
      # The 'prepublishOnly' script in package.json (npm run build) handles linting, formatting, and building.
      # If you prefer an explicit build step in CI:
      # - name: Build package
      #   run: npm run build

      - name: Release
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
>>>>>>>> main:.github/workflows/publish.yml
