---
name: Prettier

on:
  pull_request:
    types: [edited, opened, reopened, synchronize]

jobs:
  prettier:
    name: Format
    runs-on: ubuntu-latest
    permissions:
      contents: write # Changed from read to write
      packages: write

    strategy:
      fail-fast: true
      matrix:
        node-version: [22.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
          ref: ${{ github.head_ref }} # Checkout the PR branch

      - name: Setup
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          registry-url: https://registry.npmjs.org
          cache: npm

      - name: Install
        run: npm install

      - name: Format
        run: npm run format:check
