---
name: ESLint

on:
  pull_request:
    types: [edited,opened,reopened,synchronize]

jobs:
  eslint:
    name: Lint
    runs-on: ubuntu-latest
    permissions:
      contents: write # Changed from read to write
      packages: write

    strategy:
      fail-fast: true
      matrix:
        node-version: [22.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
          ref: ${{ github.head_ref }} # Checkout the PR branch

      - name: Setup
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          registry-url: https://registry.npmjs.org
          cache: npm

      - name: Install
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          # Check if there are staged changes
          if ! git diff --staged --quiet; then
            git commit -m "chore: linter syntax corrections"
            git push
          else
            echo "No changes to commit."
          fi
