---
name: Linter

on:
  pull_request:
    types: [edited,opened,reopened,synchronize]

jobs:
  linter:
    name: Lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      fail-fast: true
      matrix:
        node-version: [22.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Setup
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          registry-url: https://registry.npmjs.org
          cache: npm

      - name: Install
        run: npm install

      - name: Lint
        run: npm run lint