name: Publish

on:
  release:
    types: [created,edited]

env:
  CI: true
  NODE_ENV: test
  NODE_OPTIONS: --max-old-space-size=4096
  GEMINI_TOKEN: ${{ secrets.GEMINI_API_KEY }}
  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GITHUB_REPOSITORY: ${{ github.repository }}

jobs:
  publish:
    name: Release
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: read

    steps:
      - name: Consume Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.release.tag_name }}

      - name: Prepare Env
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          registry-url: https://registry.npmjs.org/
          cache: npm

      - name: Install Deps
        run: npm clean-install

      - name: Deploy Lib
        run: npm publish --access public --registry https://registry.npmjs.org/
