name: Publish

on:
  release:
    types:
      - published

permissions:
  contents: read
  packages: write

jobs:
  publish:
    name: Build & Release
    strategy:
      matrix:
        node-version:
          - 18.x
          - 20.x
      fail-fast: true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Setup
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          registry-url: https://registry.npmjs.org
          cache: npm

      - name: Install
        run: npm clean-install

      - name: Build
        run: npm run build

      - name: Release
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
