---
name: Validate

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - ready_for_review
      - review_requested
      - synchronize

jobs:
  validate:
    name: Analyze
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true
      - name: Setup
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install
        run: |
          npm install prettier typescript c8 dts-bundle-generator \
            eslint eslint-config-prettier eslint-plugin-markdown \
            eslint-plugin-prettier eslint-plugin-yaml@1.0.3 \
          && npm clean-install
      - name: Lint
        run: eslint . --config=./.github/linters/eslint.config.js --ext .js --report-unused-disable-directives
      - name: Format
        run: prettier --config=./.github/linters/.prettierrc.yml . --check --ignore-unknown
      - name: Test
        run: node --no-warnings --experimental-specifier-resolution=node --inspect-brk test --reporter=spec ./**/*.test.js
      - name: Build
        run: tsc
