---
name: Validate

on:
  pull_request:
    types: [edited,opened,reopened,synchronize]

jobs:
  validate:
    name: Lint & Format
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read

    strategy:
      fail-fast: true
      matrix:
        node-version: [22.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
          ref: ${{ github.event.pull_request.head.sha }} # Checkout the PR branch securely

      - name: Setup
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          registry-url: https://registry.npmjs.org
          cache: npm

      - name: Install
        run: npm install

      - name: Checks
        run: npm run lint:check
